### ISSUE TITLE
Error on Refresh (F5)

### ISSUE THREAD

**Issue by iegik** [zaggino/brackets-electron#68]
### Prerequisites
- [x] Is this `Brackets-Electron` specific problem (did you test it with latest [brackets build](http://brackets.io/))?
### Description

Exception on refresh
### Versions

v1.8.1
### Steps to Reproduce
1. Open project
2. Press [F5] key

**Expected behavior:** [What you expected to happen]

No errors

**Actual behavior:** [What actually happened]

Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at callMainWindowConsole (/opt/Brackets-Electron/resources/app/utils.js:17:19)
    at Console.c.(anonymous function) [as info](/opt/Brackets-Electron/resources/app/utils.js:29:31)
    at Object.info (/opt/Brackets-Electron/resources/app/utils.js:35:36)
    at EventEmitter.<anonymous> (/opt/Brackets-Electron/resources/app/shell.js:15:12)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/Brackets-Electron/resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by zaggino** [comment]
This should be now fixed in https://github.com/zaggino/brackets-electron/releases/tag/v1.8.2
Please re-open if that's not the case. Thanks!
